### ISSUE TITLE
Include message when triggering content preferences are updated by users

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#611] opened 2023-09-26 14:18 UTC
### Summary

Users have the option of toggling to allow them to see more content which may be triggering. The stories automatically update but this is confusing because people are not always aware the viewable content has changed. 

### What needs to be done?

- [ ] Include a simple clear confirmation message once changes have been made to the triggering content toggles (e.g. "you have successfully changed the stories you would like to view and stories containing, x, y, and z are now visible.)

**Comment by gedankenstuecke** [comment] 2023-09-26 14:20
Closing this one as it's a duplicate of #606 🙂

**Closed by gedankenstuecke** 2023-09-26 14:20 UTC
Labels: enhancement
