### ISSUE TITLE
Suggestion: Split large Milestone 3 tasks into smaller tasks to allow contributors to help complete these large tasks

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutSPACEs#167] opened 2021-09-28 11:37 UTC
### Summary

Currently we have multiple large issues mapped out to complete Milestone 3:
- [ ] #161
- [x] #158
- [x] #157
- [x] #162
- [x] #156
- [x] Implement My Stories page (#153)
- [x] #166

It **_might_** make it simpler for contributors to complete these issues by splitting them into smaller issues. 

This **_could_** help ensure momentum and understanding the wider end to end development process of that issue. 

This is **OPTIONAL** and simply a suggestion for those who may be struggling to complete the issue. 

### Deadline 

31/10/21

### What needs to be done?

- [ ] Scope out high-level issue
- [ ] Split it into smaller tasks 
- [ ] Create an issue for each smaller task 
- [ ] Post your issues on Slack to share with the wider community

### Who can help?

Assignees of the larger tasks

**Comment by callummole** [comment] 2023-01-25 12:10
Closing this issue since it is now a duplicate of #140

**Closed by callummole** 2023-01-25 12:10 UTC
Labels: Repo refresh
