### ISSUE TITLE
Create a means for moderators to access private page. 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#129] opened 2021-07-13 09:34 UTC
### Summary

With respect to the user flow diagram, there must be a way for moderators to access a private page. This could be by being given additional permission by an admin.

### What needs to be done?

- [ ] Investigate more of the open humans backend 
- [ ] design a more detailed user flow for moderators 
- [ ] build basic version

**Comment by GeorgiaHCA** [comment] 2021-07-13 09:35
@gedankenstuecke would you have a moment sometime to help @anoura12 with this?

**Comment by GeorgiaHCA** [comment] 2021-07-13 09:38
Look at the anonymous messaging system in Open Humans

**Comment by GeorgiaHCA** [comment] 2021-07-13 09:52
Possible solutions: 

- Someone in Django admin can add some users as moderators (@badgermind)

**Comment by GeorgiaHCA** [comment] 2021-07-13 09:58
The next stage of this is to design a flow of data, interaction, and access for the moderation process.

**Comment by gedankenstuecke** [comment] 2021-07-13 10:00
Happy to help, are there any clear questions on this? 

Open Humans itself doesn't provide a flow for this kind of 'metadata' or permissions for users, so it would need to be implemented in the AutSPACEs website itself. The simplest solution would indeed be adding an extra flag to the user accounts in the AutSPACEs django app which allows users to see the moderation interface on the website. This could be done through an additional model or a new column in one of the existing user/account models.

**Comment by jhlink** [comment] 2021-07-22 11:22
@gedankenstuecke , makes sense. 
I'm thinking of creating an AutSPACE-user model, which inherits from the `OpenHumansMember` model, and adding that . The latter isn't an abstract base class, so opting for [Multi-Table inheritance](https://docs.djangoproject.com/en/3.2/topics/db/models/#multi-table-inheritance) might be our only option. 

The problem is access control. 

How can we prevent the scenario where the user could manually modify the page source to say that he/she is a `Moderator`? The best way I can think of is implementing some sort of access control on the backend. A user requesting for Moderator data is verified against the database of AutSPACE users on the backend. Implementing this on the frontend, that is verifying that the user is an authentic moderator, won't be secure inherently. 

Do you have any other possible implementations around this, @gedankenstuecke ?

**Comment by gedankenstuecke** [comment] 2021-07-22 11:51
Yes, I did not mean to suggest using any frontend validation but doing it in the backend through the user authentication. You are already using the internal django authentication system if you use the `django-open-humans` library. The `OpenHumansMember` [links to the django `User`](https://github.com/OpenHumans/django-open-humans/blob/master/openhumans/models.py#L47). 

So the easiest would be to create a new `Moderator` model which has a one-to-one relationship either with the `OpenHumansMember` model or the django `User`model. You can give this model a boolean column for `is_moderator` or similar to flag whether that user account has moderation rights or not. 

For the MVP the easiest would be not implementing any frontend to flip that flag for admins but just use the existing django admin backend.

**Comment by jhlink** [comment] 2021-08-10 09:56
Closing. The ticket describes scoping to complete rather than the tasks needed to implement the feature.

**Closed** 2021-08-10 09:56 UTC
Labels: Milestone 3
