### ISSUE TITLE
Create "My stories" MVP page

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#19] opened 2021-01-20 15:05 UTC
### Summary

Create an MVP version of a private page where logged-in viewers can see and edit their own data and permissions.

A wireframe MVP of the my stories page may be found [here](https://www.figma.com/file/HxqTSdeyAUNMualnBV0PET/Autspace-(WIP)?node-id=182%3A0)

MVP requirements may be found [here](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/platform-designs/platform-requirements/mvp-requirements-list.md). 

### What needs to be done

- [x] Add navigation bar
  - [x] Add `Home` button, which directs the user to the landing page. 
  - [x] Add `View Experiences` button, which directs user to view experiences page. 
      - (A placeholder URL will suffice.)
  - [x] Add `My Stories` button, which directs user to `My Stories` page (current page). 
      - Display *only* to signed-in user
      - [x] Redirects to `Home` page if page is reloaded after user logs out. 
  - [x] Add `Share Experiences` button, which directs user to view experiences page. 
      - (A placeholder URL will suffice.)
      - Display *only* to signed-in user
  - [x] Add  `Logout` button, which logs current user out. 
      - Display *only* to signed-in user
- [x] Add title, "my stories"
- [x] Add text under title
  - [x] "See the experiences you have saved and submitted."
  - [x] "Change sharing permissions for your experiences."
- [x] Add "My Experiences" subtitle. 

### Archived
The following tasks are to be handled in the next milestone. Placed here for posterity. 
- Display user's stories (#99, #102)
- Display story submission/permission state (links to #20)
- Give option to edit individual stories - changes experience in OH database (#99 )
- Give option to change individual story permissions - changes tags in OH database (#99)

### Who can help

* Anyone with web development skills to build
* Anyone from the community to review and test*
* the designs are already founded on substantial community feedback and user testing

**Comment by GeorgiaHCA** [comment] 2021-05-18 16:05
Are you able to take this on @sowmya9507 ?

**Comment by sowmya9507** [comment] 2021-05-24 10:23
@GeorgiaHCA I will take this up and working on this.

**Comment by GeorgiaHCA** [comment] 2021-05-24 11:17
Thanks @sowmya9507 !

**Comment by mridubhatnagar** [comment] 2021-06-11 11:45
Hi, I am interested in working on this issue.

cc @lottycoupat

**Comment by israelvictory** [comment] 2021-06-11 12:04
Hello @mridubhatnagar! I've just been assigned to this issue by @sowmya9507.

**Comment by jhlink** [comment] 2021-06-16 11:27
@lottycoupat , review and feedback please!! :) 

@israelvictory , I hope this hasn't impacted too much of your progress!! 🙏

**Comment by lottycoupat** [comment] 2021-06-16 11:44
@jhlink looks great for this one!!!

**Comment by israelvictory** [comment] 2021-06-16 12:54
@jhlink not at all! Looks great to me. ✨

**Comment by lottycoupat** [comment] 2021-06-21 10:09
@israelvictory How's the progress on this page going?

**Comment by israelvictory** [comment] 2021-06-21 14:49
@lottycoupat fine! I have done almost everything that needs to be done, I'm still finding it difficult to log in to open humans. Hopefully, I figure out what the problem is and get it fixed at the latest tomorrow.

**Comment by israelvictory** [comment] 2021-06-21 15:23
@jhlink @sowmya9507 hey, you think you could help me figure out what's going on here? I'm trying to log in to open humans from the project, and I keep getting "Error: invalid_request". I have set my client id and client secret keys placed properly in my .env file; and also in my project on open humans, I have the redirect URL set to "http://localhost:8000/openhumans/complete".

**Comment by jhlink** [comment] 2021-06-21 16:16
Hey @israelvictory , for sure. 

Are you running the docker script `./docker-run.sh`? (I believe this is what is called.)

Does your `.env` also include the following? 
`OPENHUMANS_APP_BASE_URL="http://localhost:8000"`

**Comment by israelvictory** [comment] 2021-06-21 16:51
@jhlink yes, I am. Of course, I have that too.

**Comment by jhlink** [comment] 2021-06-21 17:08
@israelvictory , are you available tomorrow for the development zoom meeting? 

I'll have more time then, but in the meantime, it seems like your environment variables aren't being sourced. 
Have you tried restarting docker and starting with a fresh copy of the main branch?

**Comment by israelvictory** [comment] 2021-06-21 17:14
@jhlink not sure, I'll try to attend. 

I think I just figured out where the problem is. 🤔 If everything go fine, I'll let you know. Thank you so much for reaching out! I'm grateful.

**Comment by jhlink** [comment] 2021-06-21 17:17
Fabulous! If not, I'll be available 10:00 AM BST until 12:00 PM BST (noon) to help out hands-on. 

Good luck!! 🤞

**Comment by lottycoupat** [comment] 2021-06-21 20:08
@jhlink @israelvictory Just a reminder that the actual zoom co-working is only fortnightly - so not one this week - but that doesn't mean you both can't catch up! Let me know if you need help with Zoom and getting a meeting up and running!

**Comment by jhlink** [comment] 2021-06-22 09:36
@israelvictory , were you able to resolve your issue? Feel free to reach out to me on slack for realtime conversation. :)

**Comment by israelvictory** [comment] 2021-06-22 23:20
@jhlink I wasn't, will do, thanks!

**Comment by jhlink** [comment] 2021-07-03 14:53
@israelvictory has implemented this page. Closing.

**Closed** 2021-07-03 14:55 UTC
Labels: Milestone 2, help wanted
